(function(g,f){var a=f(g||{});if(typeof module!='undefined'&&module.exports)module.exports=a;if(g&&g.document&&g.location)a.install()})(typeof window!='undefined'?window:globalThis,function(w){'use strict';
var S={liked:new Set,subs:new Set,v2c:new Map,ctx:null,key:null,hdr:{},ready:false,p:null,fetch0:null,installed:false,errors:[]};
var REASON='Only videos you liked or videos from channels you subscribe to are available.';
function obj(x){return x&&typeof x=='object'}
function walk(x,fn,path){path=path||[];if(!obj(x))return;fn(x,path);if(Array.isArray(x)){for(var i=0;i<x.length;i++)walk(x[i],fn,path.concat(i))}else Object.keys(x).forEach(function(k){walk(x[k],fn,path.concat(k))})}
function cid(x){var r=null;walk(x,function(o){if(r)return;var a=[o.channelId,o.externalChannelId,o.browseId,o.browseEndpoint&&o.browseEndpoint.browseId];for(var i=0;i<a.length;i++)if(typeof a[i]=='string'&&/^UC[\w-]+$/.test(a[i])){r=a[i];break}});return r}
function vid(x){if(!obj(x))return null;return typeof x.videoId=='string'?x.videoId:x.videoDetails&&x.videoDetails.videoId||x.watchEndpoint&&x.watchEndpoint.videoId||x.navigationEndpoint&&x.navigationEndpoint.watchEndpoint&&x.navigationEndpoint.watchEndpoint.videoId||x.innertubeCommand&&x.innertubeCommand.watchEndpoint&&x.innertubeCommand.watchEndpoint.videoId||null}
function vnode(x){return !!(obj(x)&&(typeof x.videoId=='string'||x.videoDetails&&x.videoDetails.videoId||x.watchEndpoint&&x.watchEndpoint.videoId||x.navigationEndpoint&&x.navigationEndpoint.watchEndpoint&&x.navigationEndpoint.watchEndpoint.videoId))}
function remember(x){var v=vid(x),c=v&&cid(x);if(v&&c)S.v2c.set(v,c)}
function ok(v,c){if(!v)return true;if(S.liked.has(v))return true;c=c||S.v2c.get(v);return !!c&&S.subs.has(c)}
function filter(x){if(Array.isArray(x)){var a=[];x.forEach(function(y){if(vnode(y)){remember(y);if(!ok(vid(y),cid(y)))return}y=filter(y);if(y!=null)a.push(y)});return a}if(!obj(x))return x;if(vnode(x)){remember(x);if(!ok(vid(x),cid(x)))return null}var ks=Object.keys(x);ks.forEach(function(k){var y=filter(x[k]);if(y==null)delete x[k];else x[k]=y});return ks.length&&!Object.keys(x).length?null:x}
function player(x){if(!obj(x))return x;var d=x.videoDetails||{},v=d.videoId||vid(x),c=d.channelId||cid(d)||cid(x);if(!v||ok(v,c))return x;delete x.streamingData;delete x.captions;delete x.storyboards;x.playabilityStatus={status:'ERROR',reason:REASON,errorScreen:{playerErrorMessageRenderer:{reason:{simpleText:REASON}}}};return x}
function liked(x,t){t=t||S.liked;walk(x,function(o,p){var k=p.length?String(p[p.length-1]):'';if(/^(playlistVideoRenderer|playlistPanelVideoRenderer|videoRenderer|gridVideoRenderer|tileRenderer)$/.test(k)){var v=vid(o);if(v)t.add(v)}});return t}
function channels(x,t){t=t||S.subs;walk(x,function(o){var a=[o.channelId,o.externalChannelId,o.browseId,o.browseEndpoint&&o.browseEndpoint.browseId];a.forEach(function(c){if(typeof c=='string'&&/^UC[\w-]+$/.test(c))t.add(c)})});return t}
function guide(x,t){t=t||S.subs;(function r(n,inside){if(!obj(n))return;if(Array.isArray(n)){n.forEach(function(v){r(v,inside)});return}Object.keys(n).forEach(function(k){var y=n[k],z=inside||k.toLowerCase().indexOf('subscription')>=0;if(z&&obj(y)){var c=y.browseId||y.channelId||y.externalChannelId||y.browseEndpoint&&y.browseEndpoint.browseId;if(typeof c=='string'&&/^UC[\w-]+$/.test(c))t.add(c)}r(y,z)})})(x,false);return t}
function cont(x){var a=[];walk(x,function(o,p){if(!p.length||p[p.length-1]!='continuationItemRenderer')return;var c=o.continuationEndpoint&&o.continuationEndpoint.continuationCommand&&o.continuationEndpoint.continuationCommand.token;if(typeof c=='string'&&a.indexOf(c)<0)a.push(c)});return a}
function json(s){try{return typeof s=='string'&&s?JSON.parse(s):null}catch(e){return null}}
function cfg(){try{var y=w.ytcfg;if(!y)return;var get=typeof y.get=='function'?function(k){return y.get(k)}:function(k){return y.data_&&y.data_[k]};S.ctx=S.ctx||get('INNERTUBE_CONTEXT');S.key=S.key||get('INNERTUBE_API_KEY')}catch(e){}}
function url(x){try{return new URL(typeof x=='string'?x:x&&x.url||'',w.location&&w.location.href||'https://www.youtube.com/')}catch(e){return null}}
function isapi(u){return u&&u.pathname.indexOf('/youtubei/v1/')>=0}
function filtapi(u){return isapi(u)&&/(browse|search|next|player|reel|music\/get_queue)/.test(u.pathname)}
function payload(u,x){return /\/player$/.test(u.pathname)?player(x):filter(x)}
function headers(h){var o={};try{var H=new w.Headers(h);H.forEach(function(v,k){o[k]=v});return o}catch(e){}if(obj(h))Object.keys(h).forEach(function(k){o[k]=h[k]});return o}
async function capture(input,init){var u=url(input);if(!isapi(u))return null;cfg();S.key=S.key||u.searchParams.get('key');var h=headers(init&&init.headers||input&&input.headers);if(Object.keys(h).length)S.hdr=h;var t='';if(init&&typeof init.body=='string')t=init.body;else try{if(input&&input.clone)t=await input.clone().text()}catch(e){}var b=json(t);if(b&&b.context)S.ctx=S.ctx||b.context;return u}
function apiurl(ep){var u=new URL('/youtubei/v1/'+ep,w.location.origin);if(S.key)u.searchParams.set('key',S.key);return u.toString()}
async function post(ep,b){var h=Object.assign({},S.hdr);h['content-type']='application/json';delete h['content-length'];var r=await S.fetch0(apiurl(ep),{method:'POST',credentials:'include',headers:h,body:JSON.stringify(Object.assign({context:S.ctx},b||{}))});if(!r.ok)throw Error(ep+' '+r.status);return r.json()}
async function pages(ep,b,collect,max){var q=[b],seen=new Set,n=0;while(q.length&&n<(max||120)){var x=await post(ep,q.shift());collect(x);n++;cont(x).forEach(function(c){if(!seen.has(c)){seen.add(c);q.push({continuation:c})}})}return n}
async function boot(){cfg();if(!S.ctx)throw Error('no context');var lo=false,so=false;S.errors=[];await Promise.all([pages('browse',{browseId:'VLLL'},liked).then(function(){lo=true}).catch(function(e){S.errors.push('liked '+e)}),pages('browse',{browseId:'FEchannels'},channels).then(function(){so=true}).catch(function(e){S.errors.push('channels '+e)}),post('guide',{}).then(function(x){guide(x);so=true}).catch(function(e){S.errors.push('guide '+e)})]);S.ready=true;if(!lo&&!so)throw Error('allowlist unavailable');return S}
function ensure(){if(S.ready)return Promise.resolve(S);if(S.p)return S.p;cfg();if(!S.ctx)return Promise.resolve(null);S.p=boot().catch(function(e){S.ready=true;S.errors.push(String(e));return S});return S.p}
async function response(r,u){try{var x=json(await r.clone().text());if(!x)return r;x=payload(u,x);var h=new w.Headers(r.headers);h.delete('content-length');h.delete('content-encoding');return new w.Response(JSON.stringify(x),{status:r.status,statusText:r.statusText,headers:h})}catch(e){return r}}
function installFetch(){if(typeof w.fetch!='function')return;S.fetch0=w.fetch.bind(w);w.fetch=async function(input,init){var u=await capture(input,init||{}),p=u?ensure():Promise.resolve(null),r=await S.fetch0(input,init);if(!u||!filtapi(u))return r;await p;if(!S.ready)await ensure();return response(r,u)}}
function installXhr(){if(typeof w.XMLHttpRequest!='function'||!S.fetch0)return;var p=w.XMLHttpRequest.prototype;if(p.__ao)return;p.__ao=1;var O=p.open,D=p.send,H=p.setRequestHeader,RT=Object.getOwnPropertyDescriptor(p,'responseText'),R=Object.getOwnPropertyDescriptor(p,'response'),M=new WeakMap;function m(x){var y=M.get(x);if(!y){y={h:{}};M.set(x,y)}return y}p.open=function(method,u){var y=m(this);y.u=url(u);y.ft=y.fj=undefined;return O.apply(this,arguments)};p.setRequestHeader=function(k,v){m(this).h[k]=v;return H.apply(this,arguments)};p.send=function(b){var x=this,y=m(x);if(isapi(y.u)){cfg();S.key=S.key||y.u.searchParams.get('key');if(Object.keys(y.h).length)S.hdr=Object.assign({},y.h);var z=typeof b=='string'&&json(b);if(z&&z.context)S.ctx=S.ctx||z.context}if(filtapi(y.u)&&!S.ready){var q=ensure();if(q&&q.then){q.then(function(){D.call(x,b)},function(){D.call(x,b)});return}}return D.call(x,b)};function text(x,s){var y=m(x);if(!filtapi(y.u)||typeof s!='string'||!s)return s;if(y.ft!==undefined)return y.ft;var z=json(s);if(!z)return s;y.fj=payload(y.u,z);return y.ft=JSON.stringify(y.fj)}try{if(RT&&RT.get&&RT.configurable!==false)Object.defineProperty(p,'responseText',{configurable:true,get:function(){return text(this,RT.get.call(this))}})}catch(e){}try{if(R&&R.get&&R.configurable!==false)Object.defineProperty(p,'response',{configurable:true,get:function(){var s=R.get.call(this),y=m(this);if(!filtapi(y.u))return s;if(this.responseType=='json'&&obj(s))return y.fj!==undefined?y.fj:(y.fj=payload(y.u,s));if((this.responseType==''||this.responseType=='text')&&typeof s=='string')return text(this,s);return s}})}catch(e){}}
function bridge(){try{if(w.HTMLMediaElementExtension&&w.HTMLMediaElement&&w.HTMLMediaElement.prototype)w.HTMLMediaElement.prototype.canPlayType=w.HTMLMediaElementExtension.canPlayType}catch(e){}}
function install(){if(S.installed)return;S.installed=true;bridge();installFetch();installXhr();cfg();if(S.ctx)ensure()}
return{install:install,state:S,allowed:ok,filterTree:filter,blockPlayerResponse:player,collectLikedVideoIds:liked,collectAllChannelIds:channels,collectGuideSubscriptionIds:guide,continuationTokens:cont,firstVideoId:vid,firstChannelId:cid,BLOCK_REASON:REASON};
});
